
DROP DATABASE IF EXISTS financefolio;
CREATE DATABASE financefolio;
USE financefolio;

CREATE TABLE user (
  user_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(45) NOT NULL,
  register_date DATETIME DEFAULT now(),
  PRIMARY KEY  (user_id),
  CONSTRAINT `unq_user_name` UNIQUE(username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE member(
  member_id SMALLINT UNSIGNED NOT NULL,
  category TINYINT UNSIGNED NOT NULL,
  income DECIMAL(10,2),
  house_area SMALLINT UNSIGNED,
  residents TINYINT UNSIGNED,
  premium_user BOOLEAN DEFAULT FALSE NOT NULL,
  PRIMARY KEY (member_id),
  CONSTRAINT `fk_user_member_id` FOREIGN KEY (member_id) REFERENCES user (user_id) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE achievements(
 achievement_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
 description VARCHAR(45),
 reward TINYINT NOT NULL DEFAULT 0,
 type ENUM('SET', 'ADD', 'SAVE', 'REV', 'ANS', 'QUE'),
 amount TINYINT NOT NULL,
 PRIMARY KEY(achievement_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE unlocked_achievements(
 achievement_id SMALLINT UNSIGNED NOT NULL,
 member_id SMALLINT UNSIGNED NOT NULL,
 CONSTRAINT `fk_member_unAch_id` FOREIGN KEY (member_id) REFERENCES member (member_id) ON DELETE RESTRICT ON UPDATE CASCADE,
 CONSTRAINT `fk_ach_unAch_id` FOREIGN KEY (achievement_id) REFERENCES achievements (achievement_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE goals(
 goal_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
 owner_id SMALLINT UNSIGNED NOT NULL,
 name VARCHAR(45),
 state ENUM('ACTIVE', 'INACTIVE') NOT NULL,
 shared BOOLEAN NOT NULL DEFAULT FALSE,
 PRIMARY KEY(goal_id),
 CONSTRAINT `fk_member_goal_id` FOREIGN KEY (owner_id) REFERENCES member (member_id) ON DELETE RESTRICT ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE question(
  question_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  body VARCHAR(200) NOT NULL,
  cdate DATE NOT NULL,
  author_id SMALLINT UNSIGNED NOT NULL,
  upvotes SMALLINT DEFAULT 0,
  downvotes SMALLINT DEFAULT 0,
  PRIMARY KEY (question_id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE comment(
  question_id SMALLINT UNSIGNED NOT NULL,
  comment_id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  body VARCHAR(100) NOT NULL,
  cdate DATE NOT NULL,
  author_id SMALLINT UNSIGNED NOT NULL,
  upvotes SMALLINT DEFAULT 0,
  downvotes SMALLINT DEFAULT 0,
  PRIMARY KEY (comment_id),
  CONSTRAINT `fk_question_id` FOREIGN KEY (question_id) REFERENCES question (question_id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_author_id` FOREIGN KEY (author_id) REFERENCES user (user_id) ON DELETE RESTRICT ON UPDATE RESTRICT
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;